src/Entity/Node.php
<?php

declare(strict_types=1);

namespace App\Entity;

use App\Repository\NodeRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: NodeRepository::class)]
class Node
{
    public const KIND_D = 'directory';
    public const KIND_F = 'file';

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 50)]
    private ?string $name = null;

    #[ORM\Column(length: 10)]
    private ?string $kind = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $modifiedAt = null;

    #[ORM\ManyToOne(targetEntity: self::class, inversedBy: 'nodes')]
    private ?self $parent = null;

    /**
     * @var Collection<int, self>
     */
    #[ORM\OneToMany(targetEntity: self::class, mappedBy: 'parent')]
    private Collection $nodes;

    #[ORM\Column]
    private ?\DateTimeImmutable $createdAt = null;

    public function __construct()
    {
        $this->nodes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getKind(): ?string
    {
        return $this->kind;
    }

    public function setKind(string $kind): static
    {
        $this->kind = $kind;

        return $this;
    }

    public function isDirectory(): bool
    {
        return self::KIND_D === $this->getKind();
    }

    public function getModifiedAt(): ?\DateTimeImmutable
    {
        return $this->modifiedAt;
    }

    public function setModifiedAt(\DateTimeImmutable $modifiedAt): static
    {
        $this->modifiedAt = $modifiedAt;

        return $this;
    }

    public function getParent(): ?self
    {
        return $this->parent;
    }

    public function setParent(?self $parent): static
    {
        $this->parent = $parent;

        return $this;
    }

    /**
     * @return Collection<int, self>
     */
    public function getNodes(): Collection
    {
        return $this->nodes;
    }

    public function addNode(self $node): static
    {
        if (!$this->nodes->contains($node)) {
            $this->nodes->add($node);
            $node->setParent($this);
        }

        return $this;
    }

    public function removeNode(self $node): static
    {
        if ($this->nodes->removeElement($node)) {
            // set the owning side to null (unless already changed)
            if ($node->getParent() === $this) {
                $node->setParent(null);
            }
        }

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): static
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function isChild(): bool
    {
        return null !== $this->getParent();
    }
}

src/Controller/NodeController.php
<?php

declare(strict_types=1);

namespace App\Controller;

use App\Entity\Node;
use App\Repository\NodeRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException;
use Symfony\Component\Routing\Attribute\Route;

class NodeController extends AbstractController
{
    public function __construct(private readonly NodeRepository $repository)
    {
    }

    #[Route('/', name: 'app_node', methods: ['GET'])]
    public function index(): Response
    {
        $nodes = $this->repository->findBy(['parent' => null]);
        $this->sortNodes($nodes);

        return $this->render('node/index.html.twig', [
            'nodes' => $nodes,
        ]);
    }

    #[Route('/children', name: 'app_node_children', methods: ['POST'])]
    public function children(Request $request): Response
    {
        $nodeId = $request->getPayload()->get('nodeId');
        $csrfToken = $request->getPayload()->get('_csrf_token');

        if (empty($nodeId) || !$this->isCsrfTokenValid("n$nodeId", $csrfToken)) {
            throw new AccessDeniedHttpException();
        }

        $nodes = $this->repository->findBy(['parent' => $nodeId]);
        $this->sortNodes($nodes);

        return $this->render('node/nodes.html.twig', [
            'nodes' => $nodes,
            'parentId' => $nodeId,
        ]);
    }

    private function sortNodes(array &$nodes): void
    {
        $sorter = static function (Node $a, Node $b): int {
            if ($a->isDirectory() && !$b->isDirectory()) {
                return -1;
            }

            if ($b->isDirectory() && !$a->isDirectory()) {
                return 1;
            }

            $an = $a->getName();
            $bn = $b->getName();

            $s = [$an, $bn];
            sort($s);

            return array_search($an, $s);
        };

        usort($nodes, $sorter);
    }
}

templates/base.html.twig
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Welcome!{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block stylesheets %}
        {{ encore_entry_link_tags('app') }}
    {% endblock %}
</head>
<body>
{% block body %}{% endblock %}
{% block javascripts %}
    {{ encore_entry_script_tags('app') }}
{% endblock %}
</body>
</html>

templates/node/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello NodeController!{% endblock %}

{% block body %}
    <div class="container">
        <div class="mt-5">
            <h1>Symfony jQuery treeTable</h1>
            <table id="tree" class="table table-bordered table-hover">
                <thead>
                <tr>
                    <th>Name</th>
                    <th>Modified Date</th>
                </tr>
                </thead>
                <tbody>
                {% include 'node/nodes.html.twig' %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

templates/node/nodes.html.twig
{% for node in nodes %}
    <tr data-tt-id="{{ node.id }}"
        data-tt-parent-id="{{ node.child ? node.parent.id }}"
        data-tt-branch="{{ node.directory ? 'true' : 'false' }}"
        data-child-url="{{ path('app_node_children') }}"
        data-csrf="{{ csrf_token('n'~node.id) }}">
        <td>{{ node.name }}</td>
        <td>{{ node.modifiedAt|date('D, d M Y H:i:s') }}</td>
    </tr>
{% else %}
    <tr data-tt-id="{{ random() }}"
        data-tt-parent-id="{{ parentId }}"
        data-tt-branch="false">
        <td colspan="2">- empty -</td>
    </tr>
{% endfor %}